### ISSUE TITLE
figma: Is it possible to automatically edit the name of the frame?

### ISSUE THREAD

**Issue by xCingular** [devduttabain/issues-datamapper-pro#2]
The plug-in is very useful. It helps me a lot!
I would like to make a small suggestion, because the frame name is displayed when exporting, which will be much more convenient.

**Comment by devduttabain** [comment]
Good suggestion, thanks. may implement in the next update.

**Comment by devduttabain** [comment]
released an update with some fixes and added a dynamic frame name generation feature.

Please check the new version
[https://www.figma.com/community/plugin/1296936218664137366/datamapper-pro-bulk-generate-frames-from-json](url)

Thanks again for your valuable feedback.

**Comment by xCingular** [comment]
that's perfect for me! thank you.
